title = "pick-full-wm"

[applications]
startups = [ "polybar" ]
excluded = [ "polybar", "rofi" ]

[layout]
main_size = [ "80%x96%", "80%x100%" ] # define per monitor
top_left = [ "0,4%", "0,0" ] # define per monitor
conditional_full = true # fill side if none
new_to_main = true # new windows fill main area, rather than send to side
swap_not_stack = true # main should replace chosen side, not go to bottom
close_box = true

[bindings]
functions = [
  { key = "d", command = "rofi -show drun" },
  { key = "t", commmand = "alacritty" },
  { key = "briu", command = "brightnessctl set +10%"},
  { key = "brid", command = "brightnessctl set 10%-"},
  { key = "volu", command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"},
  { key = "vold", command = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"},
  { key = "mute", command = "wpctl set-mute @DEFAULT_SINK@ toggle" }
]
swaps = [ "j", "k", "l", ";", "u", "i", "o", "p" ]
close_main = "q"
fullscreen = "f"
help = "h"
key_hints = true
workspaces = [ "1", "2", "3", "4" ] # also defines how many
monitor = "tab" # cycle monitor index (hold shift for monitor move)
