title = "pick-full-wm"

[applications]
startups = [ "polybar", "rofi -show drun" ]
launcher = "rofi -show drun"
excluded = [ "polybar", "rofi" ]
terminal = "alacritty"

[layout]
main_size = "80%x96%"
#main_size = "1800x1080"
top_left = "0,4%"
conditional_full = true # fill side if none

[bindings]
launcher = "space"
swaps = [ "j", "k", "l", ";", "u", "i", "o", "p" ]
close_main = "q"
fullscreen = "f"
help = "h"
key_hints = true
terminal = "t"
workspaces = [ "1", "2", "3", "4" ] # also defines how many
