title = "pick-full-wm"

[applications]
startups = [ "xfce4-panel" ]
excluded = [ "xfce" ]

[layout]
main_size = [ "80%x97%", "80%x100%" ] # define per monitor
top_left = [ "0,3%", "0,0" ] # define per monitor
conditional_full = true # fill side if none
new_to_main = true # new windows fill main area, rather than send to side
swap_not_stack = true # main should replace chosen side, not go to bottom
close_box = true

[bindings]
swaps = [ "j", "k", "l", ";", "u", "i", "o", "p" ]
close_main = "q"
fullscreen = "f"
help = "h"
key_hints = false
workspaces = [ "1", "2", "3", "4" ] # also defines how many
monitor = "tab" # cycle monitor index (hold shift for monitor move)

[bindings.functions]
t = "alacritty"
b = "firefox-esr"
briu = "brightnessctl set +10%"
brid = "brightnessctl set 10%-"
volu = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
vold = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
mute = "wpctl set-mute @DEFAULT_SINK@ toggle"
